from fastapi import FastAPI

app = FastAPI()


@app.get("/stam")
async def root():
    return {"message": "Hello World"}


@app.get("/sum")
async def sum_numbers(a: int, b: int):
    return {"sum": a + b}
